Feat/criar tela de gerenciar professores
SIEHP/siehp-webapp pull request #39
Opened 2024-05-13 23:49 UTC by Vitordotpy

## Descrição

Foi criado a tela de gerenciamento de professores no modulo de `admin` para tal foram criados também os componentes `CustomTable` e `AdminPagesHeader` que representam respectivamente a tabela de informações  e o cabeçalho de cada página do administrador, a rota para acessar a página criada foi definida como `siehp.com/admin/professores`, um erro de hidratation relacionado a tabela ainda persiste, porém não afeta o funcionamento da página e pode ser resolvido em uma issue futura.

2024-05-14 15:03 UTC, CauanS29 requested changes

2024-05-14 15:03 UTC, CauanS29 commented on src/app/(client-side)/layout.tsx
> +  console.log(auth);
ficou um console.log aqui, foi proposital ? 
Para que serve essa função use AuthStore ?

2024-05-14 15:03 UTC, CauanS29 commented on src/shared/infra/presentation/components/Collapsible/index.tsx
Para o que serve esse Collapsible ?

2024-05-14 15:03 UTC, CauanS29 commented on src/shared/infra/presentation/components/SideBar/index.tsx
> +  const activeSubItem = subItems.find((item) => pathname === item.link);
nesse SideBarItem quando você ta usando o usePathName para carregar os itens ele está carregando o item inteiro ou apenas os subitens ? 
Ex: 
Ver turmas > 
   Turma A 
   Turma B 
   
Usando o pathname junto com o link você esta dando um pre-fetching em tudo de ver turmas ou apenas em uma turma em especifico ?

2024-05-14 15:03 UTC, CauanS29 commented on src/shared/infra/presentation/layouts/AppLayout/index.tsx
> +      <body className={`[&>*::-webkit-scrollbar]:w-3 min-h-dvh relative ${roboto.className}`}>
Essa é pasta principal de layout ? 
se for é realmente bom colocar essa estilização dentro desse layout ? já que muita gente pode herdar esse className

2024-05-14 15:03 UTC, CauanS29 commented on src/shared/infra/utils/constants/status_colors.ts
> +    ACTIVE: 'sucess',
acho que a palavra correta é success

2024-05-14 19:13 UTC, Vitordotpy reviewed
comentários revisados

2024-05-14 19:13 UTC, Vitordotpy commented on src/app/(client-side)/layout.tsx
> +  console.log(auth);
foram testes que adriel estava fazendo porque o auth não tava funcionando, aí ele estava tentando puxar o auth (que contém o user dentro), mas não estava vindo nada, isso aí pode ser removido na issue relacionada a consertar a autenticação.
a useAuthStore recupera o objeto auth e o usuario.

2024-05-14 19:13 UTC, Vitordotpy commented on src/shared/infra/presentation/components/Collapsible/index.tsx
é o dropdown menu da navbar

2024-05-14 19:13 UTC, Vitordotpy commented on src/shared/infra/presentation/components/SideBar/index.tsx
> +  const activeSubItem = subItems.find((item) => pathname === item.link);
apenas os subitens, ele verifica se algum subitem daquele item faz parte do path, se sim então utiliza isso para trocar a cor tanto do item como dos subitens.

tudo de turmas.

2024-05-14 19:13 UTC, Vitordotpy commented on src/shared/infra/presentation/layouts/AppLayout/index.tsx
> +      <body className={`[&>*::-webkit-scrollbar]:w-3 min-h-dvh relative ${roboto.className}`}>
não, pq essa estilização da scrollbar está sendo passada diretamente para a scroll do navegador e não dos filhos e as  outras estilizações são bem gerais e são sobrescritas pelos filhos se eles tiverem as mesmas classes setadas.

2024-05-14 19:13 UTC, Vitordotpy commented on src/shared/infra/utils/constants/status_colors.ts
> +    ACTIVE: 'sucess',
pode pá, mas quando for feita a integração eu corrigo isso, eu so tava testando se conseguia pegar esse valor dentro do componente.

2024-05-17 23:19 UTC, CauanS29 approved these changes

2024-05-17 23:19 UTC, merged