Feat/criar tela de login
SIEHP/siehp-webapp pull request #41
Opened 2024-05-24 23:33 UTC by athena272

## Descrição

Criação de tela login e navbar no head

2024-05-26 19:10 UTC, CauanS29 requested changes

2024-05-26 19:10 UTC, CauanS29 commented on src/app/page.tsx
> +      {/* <MakeWorkInProgressPage /> */}
era pra isso ficar comentado mesmo ?

2024-05-26 19:10 UTC, CauanS29 commented on src/shared/infra/presentation/layouts/LandingPageLayout/Header/index.tsx
> +              Fale Conosco
adicionaram esses links na landing page de apresentação ?

2024-05-26 19:14 UTC, CauanS29 commented
@oriajsan @athena272, deixa mais especifico o que vocês fizeram nos commits. 
Ex.: feat(Index): update header links (só um exemplo) 
em vez de : update index.ts 
fica mais fácil pra ler o código no PR, quando tá mais detalhado o commit

2024-05-27 23:35 UTC, Vitordotpy commented on src/app/page.tsx
> +      {/* <MakeWorkInProgressPage /> */}
é bom, pq vai que entra em manutenção o sistema, a gente pode reutilizar essa tela aí, no lugar da de login.

2024-05-27 23:37 UTC, Vitordotpy commented on src/shared/infra/presentation/layouts/LandingPageLayout/Header/index.tsx
> +              Fale Conosco
eles deixaram sem link, para poder colocar depois, eu que mandei.

2024-05-28 00:17 UTC, Vitordotpy approved these changes
foda muito foda

2024-05-28 00:18 UTC, merged